CREATE TABLE IF NOT EXISTS Student(
	NUM INT NOT NULL,
	PWD VARCHAR(20),
	DEPART VARCHAR(20), 
	NAME VARCHAR(30),
	ADDRESS VARCHAR(50),
	PHONE VARCHAR(20),
	EMAIL VARCHAR(30),
	PRIMARY KEY (NUM)
);

SELECT * FROM student;